### ISSUE TITLE
Install Helix Databases in Package?

### ISSUE THREAD

**Issue by kyleabeauchamp** [fcchou/HelixMC#1]
So it might be convenient (for users, not for you) to have setuptools automatically install the database files inside of the package.  

It should be possible to do this with a couple of extra lines to setup.py.  You can then access the files using `pkg_resources` library:

```
    dih_filename = pkg_resources.resource_filename("fit_ensemble","example_data/rama.npz")

```

I've _tried_ to do this with fit_ensemble (see setup.py and src/example_loader.py).  I should point out that I experienced a bit of difficulty getting this to work right--there seemed to be some problems with the various tutorials I found on the internet.

**Comment by fcchou** [comment]
Issue resolved.
